version: '3.8'

services:
    sql-server-db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: bulky-sql-server-db
        restart: always
        volumes:
            - ./Databases/sql-server:/var/opt/mssql/data
        environment:
            - SA_PASSWORD=S3cur3P@ssW0rd!
            - ACCEPT_EULA=Y
        ports:
            - "16001:1433"
        networks:
            - bulky-network    
networks:
    bulky-network:
        external: true